import type { PointsOfInterestProps } from '../../../content.config';

export const SORT_ORDER: (keyof PointsOfInterestProps)[] = [
  'id',
  'latitude',
  'longitude',
  'img',
  'thermalImg',
  'originalSegImg',
  'customSegImg',
  'redHSV',
  'yellowHSV',
  'greenHSV',
  'cyanHSV',
  'blueHSV',
  'magentaHSV',
  'redMean',
  'greenMean',
  'blueMean',
  'redStdDev',
  'greenStdDev',
  'blueStdDev',
  'skySegmentationPercent',
  'pavementSegmentationPercent',
  'waterSegmentationPercent',
  'vegetationSegmentationPercent',
  'buildingSegmentationPercent',
  'otherSegmentationPercent',
  'concreteSurface',
  'grassSurface',
  'asphaltSurface',
  'woodSurface',
  'brickSurface',
  'gravelSurface',
  'tilesSurface',
  'rubber',
  'buildingShade',
  'treeShade',
  'shadeProvision',
  'restSpotOutdoorFurniture',
  'waterFeature',
  'thermalRatio',
];

export const TITLE_MAPPINGS: { [key in keyof PointsOfInterestProps]: string } = {
  id: 'id',
  latitude: 'Latitude',
  longitude: 'Longitude',
  img: 'Image',
  thermalImg: 'Thermal Image',
  redHSV: 'Red (HSV)',
  yellowHSV: 'Yellow (HSV)',
  greenHSV: 'Green (HSV)',
  cyanHSV: 'Cyan (HSV)',
  blueHSV: 'Blue (HSV)',
  magentaHSV: 'Magenta (HSV)',
  redMean: 'Mean of Red Channel',
  greenMean: 'Mean of Green Channel',
  blueMean: 'Mean of Blue Channel',
  redStdDev: 'Standard Deviation of Red Channel',
  greenStdDev: 'Standard Deviation of Green Channel',
  blueStdDev: 'Standard Deviation of Blue Channel',
  skySegmentationPercent: 'Sky Segmentation Percentage',
  pavementSegmentationPercent: 'Pavement Segmentation Percentage',
  waterSegmentationPercent: 'Water Segmentation Percentage',
  vegetationSegmentationPercent: 'Vegetation Segmentation Percentage',
  buildingSegmentationPercent: 'Building Segmentation Percentage',
  otherSegmentationPercent: 'Other Segmentation Percentage',
  concreteSurface: 'Concrete Surface Material',
  grassSurface: 'Grass Surface Material',
  asphaltSurface: 'Asphalt Surface Material',
  woodSurface: 'Wood Surface Material',
  brickSurface: 'Brick Surface Material',
  gravelSurface: 'Gravel Surface Material',
  tilesSurface: 'Tiles Surface Material',
  rubber: 'Rubber',
  buildingShade: 'Building Shade',
  treeShade: 'Tree Shade',
  shadeProvision: 'Shade Provision',
  restSpotOutdoorFurniture: 'Rest Spot / Outdoor Furniture',
  waterFeature: 'Water Feature',
  thermalRatio: 'Thermal Ratio',
};
